export const REFRESH_SECTION_REQUEST = 'sections/REFRESH_SECTION_REQUEST';
export const REFRESH_SECTION_SUCCESS = 'sections/REFRESH_SECTION_SUCCESS';

export const FETCH_SECTION_NEXT_PAGE_REQUEST = 'sections/FETCH_SECTION_NEXT_PAGE_REQUEST';
export const FETCH_SECTION_NEXT_PAGE = 'sections/FETCH_SECTION_NEXT_PAGE';
export const FETCH_SECTION_NEXT_PAGE_SUCCESS = 'sections/FETCH_SECTION_NEXT_PAGE_SUCCESS';
