export const EXPLORE_MOVIES_LOAD_REQUEST = 'explore/EXPLORE_MOVIES_LOAD_REQUEST';
export const EXPLORE_MOVIES_LOAD = 'explore/EXPLORE_MOVIES_LOAD';
export const EXPLORE_MOVIES_LOAD_SUCCESS = 'explore/EXPLORE_MOVIES_LOAD_SUCCESS';
export const EXPLORE_MOVIES_POSTERS_LOADED = 'explore/EXPLORE_MOVIES_POSTERS_LOADED';

export const EXPLORE_ACTION_RESOLVED = 'explore/EXPLORE_ACTION_RESOLVED';

export const EXPLORE_MOVIE_SWIPED = 'explore/EXPLORE_MOVIE_SWIPED';
