export const Auth = {
  USERNAME_CHANGED: 'auth/USERNAME_CHANGED',
  USERNAME_INCORRECT: 'auth/USERNAME_INCORRECT',
  PASSWORD_CHANGED: 'auth/PASSWORD_CHANGED',
  PASSWORD_INCORRECT: 'auth/PASSWORD_INCORRECT',
  LOGIN_USER_ATTEMPT: 'auth/LOGIN_USER_ATTEMPT',
  LOGIN_USER_SUCCESS: 'auth/LOGIN_USER_SUCCESS',
  LOGIN_USER_FAIL: 'auth/LOGIN_USER_FAIL',

  CREATE_GUEST_SESSION_ATTEMPT: 'auth/CREATE_GUEST_SESSION_ATTEMPT',
  CREATE_GUEST_SESSION_SUCCESS: 'auth/CREATE_GUEST_SESSION_SUCCESS',
  CREATE_GUEST_SESSION_FAIL: 'auth/CREATE_GUEST_SESSION_FAIL',

  CLEAR_LOGIN_FIELDS: 'auth/CLEAR_LOGIN_FIELDS',
  USER_LOADED: 'auth/USER_LOADED',
  LOG_OUT: 'auth/LOG_OUT'
};
