export const INITIATE_NETWORK_MONITORING = 'network/INITIATE_NETWORK_MONITORING';
export const STOP_NETWORK_MONITORING = 'network/STOP_NETWORK_MONITORING';

export const CHECK_NETWORK_CONNECTION = 'network/CHECK_NETWORK_CONNECTION';
export const NETWORK_STATE_CHANGED = 'network/NETWORK_STATE_CHANGED';

export const HANDLE_NETWORK_REDUX_ERROR = 'network/HANDLE_NETWORK_REDUX_ERROR';
export const NETWORK_REDUX_ERRORS_RESOLVED = 'network/NETWORK_REDUX_ERRORS_RESOLVED';
export const CLEAR_REDUX_ACTIONS_FROM_QUEUE = 'network/CLEAR_REDUX_ACTIONS_FROM_QUEUE';
