export const SEARCH_TEXT_CHANGED = 'search/SEARCH_TEXT_CHANGED';

export const CLEAR_SEARCH_RESULTS = 'search/CLEAR_SEARCH_RESULTS';

export const SEARCH_MOVIES_REQUEST = 'search/SEARCH_MOVIES_REQUEST';
export const SEARCH_MOVIES_REQUEST_SLOW = 'search/SEARCH_MOVIES_REQUEST_SLOW';
export const SEARCH_MOVIES_SUCCESS = 'search/SEARCH_MOVIES_SUCCESS';

export const SEARCH_MOVIES_PAGINATION_REQUEST = 'search/SEARCH_MOVIES_PAGINATION_REQUEST';
export const SEARCH_MOVIES_PAGINATION_FETCH = 'search/SEARCH_MOVIES_PAGINATION_FETCH';
export const SEARCH_MOVIES_PAGINATION_SUCCESS = 'search/SEARCH_MOVIES_PAGINATION_SUCCESS';
