export const CREATE_AUTHENTICATED_SESSION_REQUEST = 'auth/CREATE_AUTHENTICATED_SESSION_REQUEST';
export const CREATE_AUTHENTICATED_SESSION_SUCCESS = 'auth/CREATE_AUTHENTICATED_SESSION_SUCCESS';
export const CREATE_AUTHENTICATED_SESSION_FAILURE = 'auth/CREATE_AUTHENTICATED_SESSION_FAILURE';

export const CREATE_GUEST_SESSION_REQUEST = 'auth/CREATE_GUEST_SESSION_REQUEST';
export const CREATE_GUEST_SESSION_SUCCESS = 'auth/CREATE_GUEST_SESSION_SUCCESS';
export const CREATE_GUEST_SESSION_FAILURE = 'auth/CREATE_GUEST_SESSION_FAILURE';

export const LOG_OUT = 'auth/LOG_OUT';
