export const ADD_MOVIES = 'movies/ADD_MOVIES';

export const FETCH_DETAILED_MOVIE_REQUEST = 'movies/FETCH_DETAILED_MOVIE_REQUEST';
export const FETCH_DETAILED_MOVIE_SUCCESS = 'movies/FETCH_DETAILED_MOVIE_SUCCESS';

export const FETCH_MOVIE_ACCOUNT_STATE_REQUEST = 'movies/FETCH_MOVIE_ACCOUNT_STATE_REQUEST';
export const FETCH_MOVIE_ACCOUNT_STATE_SUCCESS = 'movies/FETCH_MOVIE_ACCOUNT_STATE_SUCCESS';

export const FETCH_MOVIE_RECOMMENDATIONS_REQUEST = 'movies/FETCH_MOVIE_RECOMMENDATIONS_REQUEST';
export const FETCH_MOVIE_RECOMMENDATIONS_SUCCESS = 'movies/FETCH_MOVIE_RECOMMENDATIONS_SUCCESS';

export const CHANGE_MOVIE_STATUS_REQUEST = 'movies/CHANGE_MOVIE_STATUS_REQUEST';
export const CHANGE_MOVIE_STATUS_SUCCESS = 'movies/CHANGE_MOVIE_STATUS_SUCCESS';
export const CHANGE_MOVIE_STATUS_FAILURE = 'movies/CHANGE_MOVIE_STATUS_FAILURE';

export const FILTER_UNUSED_MOVIE_DATA = 'movies/FILTER_UNUSED_MOVIE_DATA';
